// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; // ✅ تم تفعيل دعم الـ iOS هنا
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtwb0fAIMq3q_YMIkHMLUD3_-GvGkYdVw',
    appId: '1:905243871570:android:d884ea928cedb56b66928b',
    messagingSenderId: '905243871570',
    projectId: 'lpro2-quiz',
    storageBucket: 'lpro2-quiz.firebasestorage.app',
  );

  // 🍎 إضافة إعدادات الـ iOS بناءً على ملف الـ Plist الخاص بك
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYT8L88sd9Vz1tvnKRg1TJZmaEi_HMZw',
    appId: '1:905243871570:ios:7dd006b803e36a4c66928b',
    messagingSenderId: '905243871570',
    projectId: 'lpro2-quiz',
    storageBucket: 'lpro2-quiz.firebasestorage.app',
    iosBundleId: 'com.george.lpro',
  );
}
