// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9G5tJJnjknRXLXbmtZb1ruHGEPsWiwU',
    appId: '1:740475912872:web:7cf9ddfd59cdc06732789d',
    messagingSenderId: '740475912872',
    projectId: 'g-lpro',
    authDomain: 'g-lpro.firebaseapp.com',
    storageBucket: 'g-lpro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOGf0pMAnfr3SpaV4oOPGQciyx48CyYw',
    appId: '1:740475912872:android:5ff41971629003eb32789d',
    messagingSenderId: '740475912872',
    projectId: 'g-lpro',
    storageBucket: 'g-lpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS7D6uUlprf1zl_OB9kjnAwpM6ynYUkLw',
    appId: '1:740475912872:ios:cce524f2f3e55fe332789d',
    messagingSenderId: '740475912872',
    projectId: 'g-lpro',
    storageBucket: 'g-lpro.firebasestorage.app',
    iosBundleId: 'com.example.lpro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS7D6uUlprf1zl_OB9kjnAwpM6ynYUkLw',
    appId: '1:740475912872:ios:cce524f2f3e55fe332789d',
    messagingSenderId: '740475912872',
    projectId: 'g-lpro',
    storageBucket: 'g-lpro.firebasestorage.app',
    iosBundleId: 'com.example.lpro2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU9G5tJJnjknRXLXbmtZb1ruHGEPsWiwU',
    appId: '1:740475912872:web:ab3d4bdd08bde87d32789d',
    messagingSenderId: '740475912872',
    projectId: 'g-lpro',
    authDomain: 'g-lpro.firebaseapp.com',
    storageBucket: 'g-lpro.firebasestorage.app',
  );
}
