// File generated by FlutterFire CLI & Manually Optimized for LPro Production
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// إعدادات Firebase الافتراضية - نسخة الإنتاج المستقرة 2026
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; // ✅ تم تفعيل المزامنة الكاملة مع AppDelegate
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🤖 إعدادات الأندرويد (تطابق ملف google-services.json)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtwb0fAIMq3q_YMIkHMLUD3_-GvGkYdVw',
    appId: '1:905243871570:android:d884ea928cedb56b66928b',
    messagingSenderId: '905243871570',
    projectId: 'lpro2-quiz',
    storageBucket: 'lpro2-quiz.firebasestorage.app',
  );

  /// 🍎 إعدادات iOS (تطابق كامل 100% مع GoogleService-Info.plist و AppDelegate.swift)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYT8L88sd9Vz1tvnKRg1TJZmaEi_HMZw',
    appId: '1:905243871570:ios:7dd006b803e36a4c66928b',
    messagingSenderId: '905243871570',
    projectId: 'lpro2-quiz',
    storageBucket: 'lpro2-quiz.firebasestorage.app',
    iosBundleId: 'com.george.lpro',
    // ✅ القيمة المضافة لضمان استقرار هوية التطبيق (تم جلبها من الـ Plist)
    iosClientId:
        '905243871570-1e1rl17ir696ml70u9ejvdev651t81f6.apps.googleusercontent.com',
  );
}
